(deftheme Spacemacs-varient

  "Created 2019-06-23.")

(custom-theme-set-faces
 'Spacemacs-varient

 '(default ((t (:family "Source Code Pro" :foundry "ADBO" :width normal :height 98 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#b2b2b2" :background "#292b2e" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#e3dedd"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#4f97d7" :inherit (bold)))))
 '(highlight ((t (:foreground "#b2b2b2" :background "#444155"))))
 '(region ((t (:background "#444155"))))
 '(shadow ((t (:foreground "#686868"))))
 '(secondary-selection ((t (:background "#100a14"))))
 '(trailing-whitespace ((t (:background "#e0211d"))))
 '(font-lock-builtin-face ((t (:foreground "#4f97d7"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant normal :foreground "#2aa1ae" :background "#292e34"))))
 '(font-lock-constant-face ((t (:foreground "#a45bad"))))
 '(font-lock-doc-face ((t (:slant normal :foreground "#9f8766" :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "#bc6ec5" :inherit (bold)))))
 '(font-lock-keyword-face ((t (:slant normal :foreground "#4f97d7" :inherit (bold)))))
 '(font-lock-negation-char-face ((t (:foreground "#a45bad" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#bc6ec5" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#6c9ef8" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#6c9ef8" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#2d9574"))))
 '(font-lock-type-face ((t (:foreground "#ce537a" :inherit (bold)))))
 '(font-lock-variable-name-face ((t (:foreground "#7590db"))))
 '(font-lock-warning-face ((t (:foreground "#dc752f" :background "#292b2e" :inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#2aa1ae"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#c56ec3"))))
 '(fringe ((t (:foreground "#b2b2b2" :background "#292b2e" :inherit (default)))))
 '(header-line ((t (:background "#0a0814" :inherit (mode-line)))))
 '(tooltip ((t (:weight normal :slant normal :underline nil :foreground "#b2b2b2" :background "#5e5079"))))
 '(mode-line ((t (:box (:line-width 1 :color "#5d4d7a" :style nil) :foreground "#b2b2b2" :background "#222226"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#bc6ec5" :inherit (bold)))))
 '(mode-line-emphasis ((t (:foreground "#fc20bb"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width 1 :color "#5d4d7a" :style nil) :foreground "#b2b2b2" :background "#292b2e"))))
 '(isearch ((t (:weight bold :foreground "#292b2e" :background "#86dc2f" :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#1b1d1e" :background "#d02b61"))))
 '(lazy-highlight ((t (:weight normal :foreground "#1b1d1e" :background "#29422d"))))
 '(match ((t (:weight bold :foreground "#86dc2f" :background "#444155"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'Spacemacs-varient
)
