;;; lex-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from lex.el

(autoload 'lex-compile "lex" "\
Compile a set of regular expressions.
ALIST is a list of elements of the form (REGEXP . VALUE).
The compiled automaton will match all those regexps at the same time
and will return the VALUE for the leftmost longest match.

Each REGEXP object should be in the sexp form described in the
Commentary section.

(fn ALIST)")
(register-definition-prefixes "lex" '("copy-char-table" "lex-"))


;;; Generated autoloads from lex-parse-re.el

(autoload 'lex-parse-re "lex-parse-re" "\
Parse STRING as a regular expression.
LEXER specifies the regexp syntax to use.  It can be `ere', or `bre'
and it defaults to `bre'.

(fn STRING &optional LEXER)")
(register-definition-prefixes "lex-parse-re" '("lex--"))

;;; End of scraped data

(provide 'lex-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lex-autoloads.el ends here
